// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkylnzagutfjvjdyberg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZreWxuemFndXRmanZqZHliZXJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Mzc4MzAsImV4cCI6MjA2NTUxMzgzMH0.SWKtaVgdLVY6CaLU1XB0pdoNZwYnNoqXjEtldE3HOh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);